version: '3.8'

services:
  php:
    build: ./docker/php
    env_file:
      - .env
    container_name: php
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./app:/var/www/enviros:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - "userroot:/root"
    working_dir: /var/www/enviros
    networks:
      - backend
    depends_on:
      - mariadb
    environment:
      APP_ENV: ${APP_ENV}
      MYSQL_SERVER: ${DB_HOST}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      XDEBUG_CONFIG: "idekey=PHPSTORM"
      PHP_IDE_CONFIG: "serverName=localhost"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./app:/var/www/enviros
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./var/log/php-xdebug.log:/var/www/log/xdebug.log
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - backend
    depends_on:
      - php
    environment:
      XDEBUG_ENABLED: 1
      XDEBUG_REMOTE_AUTOSTART: 1
      XDEBUG_MAXNESTING_LEVEL: 1000
      XDEBUG_REMOTE_CONNECT_BACK: 1
      XDEBUG_REMOTE_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: 9008
      APP_ENV: dev
      PHP_IDE_CONFIG: serverName=localhost

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    volumes:
      - ./var/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

volumes:
  userroot:

networks:
  backend: