version: '3.8'

services:
  php:
    build: ./php
    env_file: .env
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./app:/var/www/enviros:cached
      - ./php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/enviros
    networks:
      - backend
      - backend_network
    environment:
      APP_ENV: ${APP_ENV}
      MYSQL_SERVER: ${DB_HOST}
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD

  nginx:
    image: nginx:latest
    env_file: .env
    volumes:
      - ./app:/var/www/enviros
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./var/log/php-xdebug.log:/var/www/log/xdebug.log
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - backend
    depends_on:
      - php
    environment:
      APP_ENV: ${APP_ENV}

volumes:
  logs:

networks:
  backend:
  backend_network:
    external: true